export type CategoryCatalogItem = {
  id: string;
  name: string;
  type: 'EXPENSE' | 'INCOME' | 'SAVING';
  purposeType: 'GENERAL' | 'SAVING' | 'INVESTMENT';
  parentCategoryId?: string;
  sortOrder: number;
  isActive?: boolean;
};

// Stable IDs are intentionally independent from Korean display names.
// The `core.` prefix separates system categories from user-created categories.
export const CATEGORY_IDS = {
  SAVING: 'core.saving',
  INVESTMENT: 'core.investment',
  EXPENSE: 'core.expense',
  INCOME: 'core.income',
  SAVING_EMERGENCY_FUND: 'core.saving.emergency-fund',
  SAVING_GOAL: 'core.saving.goal',
  SAVING_INSTALLMENT: 'core.saving.installment',
  SAVING_DEPOSIT: 'core.saving.deposit',
  SAVING_HOUSING: 'core.saving.housing',
  SAVING_PENSION: 'core.saving.pension',
  INVESTMENT_STOCK: 'core.investment.stock',
  INVESTMENT_ETF: 'core.investment.etf',
  INVESTMENT_FUND: 'core.investment.fund',
  INVESTMENT_BOND: 'core.investment.bond',
  INVESTMENT_CRYPTO: 'core.investment.crypto',
  INVESTMENT_PENSION: 'core.investment.pension',

  EXPENSE_HOUSING: 'core.expense.housing',
  EXPENSE_FOOD: 'core.expense.food',
  EXPENSE_FOOD_MEAL: 'core.expense.food.meal',
  EXPENSE_FOOD_DELIVERY: 'core.expense.food.delivery',
  EXPENSE_FOOD_CAFE: 'core.expense.food.cafe',
  EXPENSE_FOOD_SNACK: 'core.expense.food.snack',
  EXPENSE_FOOD_ALCOHOL: 'core.expense.food.alcohol',
  EXPENSE_FOOD_CONVENIENCE: 'core.expense.food.convenience',
  EXPENSE_TRANSPORT: 'core.expense.transport',
  EXPENSE_TRANSPORT_PUBLIC: 'core.expense.transport.public',
  EXPENSE_TRANSPORT_TAXI: 'core.expense.transport.taxi',
  EXPENSE_TRANSPORT_INTERCITY: 'core.expense.transport.intercity',
  EXPENSE_TRANSPORT_FUEL: 'core.expense.transport.fuel',
  EXPENSE_TRANSPORT_PARKING: 'core.expense.transport.parking',
  EXPENSE_TRANSPORT_MAINTENANCE: 'core.expense.transport.maintenance',
  EXPENSE_LIVING: 'core.expense.living',
  EXPENSE_LIVING_NECESSITIES: 'core.expense.living.necessities',
  EXPENSE_LIVING_GROCERY: 'core.expense.living.grocery',
  EXPENSE_COMMUNICATION: 'core.expense.communication',
  EXPENSE_LIVING_UTILITIES: 'core.expense.living.utilities',
  EXPENSE_LIVING_SUBSCRIPTION: 'core.expense.living.subscription',
  EXPENSE_SHOPPING: 'core.expense.shopping',
  EXPENSE_SHOPPING_CLOTHING: 'core.expense.shopping.clothing',
  EXPENSE_SHOPPING_SHOES_ACCESSORIES: 'core.expense.shopping.shoes-accessories',
  EXPENSE_SHOPPING_BEAUTY: 'core.expense.shopping.beauty',
  EXPENSE_SHOPPING_ELECTRONICS: 'core.expense.shopping.electronics',
  EXPENSE_SHOPPING_FURNITURE: 'core.expense.shopping.furniture',
  EXPENSE_SHOPPING_OTHER: 'core.expense.shopping.other',
  EXPENSE_LEISURE_CULTURE: 'core.expense.leisure-culture',
  EXPENSE_LEISURE_MOVIE_PERFORMANCE: 'core.expense.leisure-culture.movie-performance',
  EXPENSE_LEISURE_GAME: 'core.expense.leisure-culture.game',
  EXPENSE_LEISURE_HOBBY: 'core.expense.leisure-culture.hobby',
  EXPENSE_LEISURE_TRAVEL: 'core.expense.leisure-culture.travel',
  EXPENSE_LEISURE_SPORTS: 'core.expense.leisure-culture.sports',
  EXPENSE_LEISURE_CONTENT: 'core.expense.leisure-culture.content',
  EXPENSE_HEALTH: 'core.expense.health',
  EXPENSE_HEALTH_HOSPITAL: 'core.expense.health.hospital',
  EXPENSE_HEALTH_PHARMACY: 'core.expense.health.pharmacy',
  EXPENSE_HEALTH_EXERCISE: 'core.expense.health.exercise',
  EXPENSE_HEALTH_MANAGEMENT: 'core.expense.health.management',
  EXPENSE_EDUCATION: 'core.expense.education',
  EXPENSE_EDUCATION_BOOK: 'core.expense.education.book',
  EXPENSE_EDUCATION_LECTURE: 'core.expense.education.lecture',
  EXPENSE_EDUCATION_ACADEMY: 'core.expense.education.academy',
  EXPENSE_EDUCATION_CERTIFICATE: 'core.expense.education.certificate',
  EXPENSE_EDUCATION_TUITION: 'core.expense.education.tuition',
  EXPENSE_RELATIONSHIP: 'core.expense.relationship',
  EXPENSE_RELATIONSHIP_FRIENDS: 'core.expense.relationship.friends',
  EXPENSE_RELATIONSHIP_DATE: 'core.expense.relationship.date',
  EXPENSE_RELATIONSHIP_GIFT: 'core.expense.relationship.gift',
  EXPENSE_RELATIONSHIP_CEREMONY: 'core.expense.relationship.ceremony',
  EXPENSE_RELATIONSHIP_MEMBERSHIP: 'core.expense.relationship.membership',
  EXPENSE_FINANCE: 'core.expense.finance',
  EXPENSE_FINANCE_FEE: 'core.expense.finance.fee',
  EXPENSE_FINANCE_INTEREST: 'core.expense.finance.interest',
  EXPENSE_FINANCE_TAX: 'core.expense.finance.tax',
  EXPENSE_INSURANCE_TAX: 'core.expense.insurance-tax',
  EXPENSE_DEBT_REPAYMENT: 'core.expense.debt-repayment',
  EXPENSE_OTHER: 'core.expense.other',
  EXPENSE_OTHER_EXPENSE: 'core.expense.other.expense',
  EXPENSE_UNCLASSIFIED: 'core.expense.unclassified',
  INCOME_SALARY: 'core.income.salary',
} as const;

export const CATEGORY_CATALOG: CategoryCatalogItem[] = [
  { id: CATEGORY_IDS.SAVING, name: '저축', type: 'SAVING', purposeType: 'SAVING', sortOrder: 10 },
  { id: CATEGORY_IDS.INVESTMENT, name: '투자', type: 'SAVING', purposeType: 'INVESTMENT', sortOrder: 20 },
  { id: CATEGORY_IDS.EXPENSE, name: '지출', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 30, isActive: false },
  { id: CATEGORY_IDS.INCOME, name: '수입', type: 'INCOME', purposeType: 'GENERAL', sortOrder: 40 },

  { id: CATEGORY_IDS.SAVING_EMERGENCY_FUND, name: '비상금', type: 'SAVING', purposeType: 'SAVING', parentCategoryId: CATEGORY_IDS.SAVING, sortOrder: 110 },
  { id: CATEGORY_IDS.SAVING_GOAL, name: '목적성 저축', type: 'SAVING', purposeType: 'SAVING', parentCategoryId: CATEGORY_IDS.SAVING, sortOrder: 120 },
  { id: CATEGORY_IDS.SAVING_INSTALLMENT, name: '적금', type: 'SAVING', purposeType: 'SAVING', parentCategoryId: CATEGORY_IDS.SAVING, sortOrder: 130 },
  { id: CATEGORY_IDS.SAVING_DEPOSIT, name: '예금', type: 'SAVING', purposeType: 'SAVING', parentCategoryId: CATEGORY_IDS.SAVING, sortOrder: 140 },
  { id: CATEGORY_IDS.SAVING_HOUSING, name: '주택청약', type: 'SAVING', purposeType: 'SAVING', parentCategoryId: CATEGORY_IDS.SAVING, sortOrder: 150 },
  { id: CATEGORY_IDS.SAVING_PENSION, name: '연금저축', type: 'SAVING', purposeType: 'SAVING', parentCategoryId: CATEGORY_IDS.SAVING, sortOrder: 160 },

  { id: CATEGORY_IDS.INVESTMENT_STOCK, name: '주식', type: 'SAVING', purposeType: 'INVESTMENT', parentCategoryId: CATEGORY_IDS.INVESTMENT, sortOrder: 210 },
  { id: CATEGORY_IDS.INVESTMENT_ETF, name: 'ETF', type: 'SAVING', purposeType: 'INVESTMENT', parentCategoryId: CATEGORY_IDS.INVESTMENT, sortOrder: 220 },
  { id: CATEGORY_IDS.INVESTMENT_FUND, name: '펀드', type: 'SAVING', purposeType: 'INVESTMENT', parentCategoryId: CATEGORY_IDS.INVESTMENT, sortOrder: 230 },
  { id: CATEGORY_IDS.INVESTMENT_BOND, name: '채권', type: 'SAVING', purposeType: 'INVESTMENT', parentCategoryId: CATEGORY_IDS.INVESTMENT, sortOrder: 240 },
  { id: CATEGORY_IDS.INVESTMENT_CRYPTO, name: '가상자산', type: 'SAVING', purposeType: 'INVESTMENT', parentCategoryId: CATEGORY_IDS.INVESTMENT, sortOrder: 250 },
  { id: CATEGORY_IDS.INVESTMENT_PENSION, name: '퇴직연금·IRP', type: 'SAVING', purposeType: 'INVESTMENT', parentCategoryId: CATEGORY_IDS.INVESTMENT, sortOrder: 260 },

  { id: CATEGORY_IDS.EXPENSE_FOOD, name: '식비', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 310 },
  { id: CATEGORY_IDS.EXPENSE_FOOD_MEAL, name: '식사', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FOOD, sortOrder: 311 },
  { id: CATEGORY_IDS.EXPENSE_FOOD_DELIVERY, name: '배달', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FOOD, sortOrder: 312 },
  { id: CATEGORY_IDS.EXPENSE_FOOD_CAFE, name: '카페', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FOOD, sortOrder: 313 },
  { id: CATEGORY_IDS.EXPENSE_FOOD_SNACK, name: '간식', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FOOD, sortOrder: 314 },
  { id: CATEGORY_IDS.EXPENSE_FOOD_ALCOHOL, name: '술', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FOOD, sortOrder: 315 },
  { id: CATEGORY_IDS.EXPENSE_FOOD_CONVENIENCE, name: '편의점', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FOOD, sortOrder: 316 },

  { id: CATEGORY_IDS.EXPENSE_TRANSPORT, name: '교통', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 320 },
  { id: CATEGORY_IDS.EXPENSE_TRANSPORT_PUBLIC, name: '대중교통', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_TRANSPORT, sortOrder: 321 },
  { id: CATEGORY_IDS.EXPENSE_TRANSPORT_TAXI, name: '택시', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_TRANSPORT, sortOrder: 322 },
  { id: CATEGORY_IDS.EXPENSE_TRANSPORT_INTERCITY, name: '기차·버스', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_TRANSPORT, sortOrder: 323 },
  { id: CATEGORY_IDS.EXPENSE_TRANSPORT_FUEL, name: '주유', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_TRANSPORT, sortOrder: 324 },
  { id: CATEGORY_IDS.EXPENSE_TRANSPORT_PARKING, name: '주차', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_TRANSPORT, sortOrder: 325 },
  { id: CATEGORY_IDS.EXPENSE_TRANSPORT_MAINTENANCE, name: '차량관리', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_TRANSPORT, sortOrder: 326 },

  { id: CATEGORY_IDS.EXPENSE_LIVING, name: '생활', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 330 },
  { id: CATEGORY_IDS.EXPENSE_LIVING_NECESSITIES, name: '생필품', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LIVING, sortOrder: 331 },
  { id: CATEGORY_IDS.EXPENSE_LIVING_GROCERY, name: '마트·장보기', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LIVING, sortOrder: 332 },
  { id: CATEGORY_IDS.EXPENSE_COMMUNICATION, name: '통신비', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LIVING, sortOrder: 333 },
  { id: CATEGORY_IDS.EXPENSE_LIVING_UTILITIES, name: '공과금', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LIVING, sortOrder: 334 },
  { id: CATEGORY_IDS.EXPENSE_HOUSING, name: '주거비', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LIVING, sortOrder: 335 },
  { id: CATEGORY_IDS.EXPENSE_LIVING_SUBSCRIPTION, name: '구독', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LIVING, sortOrder: 336 },

  { id: CATEGORY_IDS.EXPENSE_SHOPPING, name: '쇼핑', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 340 },
  { id: CATEGORY_IDS.EXPENSE_SHOPPING_CLOTHING, name: '의류', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_SHOPPING, sortOrder: 341 },
  { id: CATEGORY_IDS.EXPENSE_SHOPPING_SHOES_ACCESSORIES, name: '신발·잡화', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_SHOPPING, sortOrder: 342 },
  { id: CATEGORY_IDS.EXPENSE_SHOPPING_BEAUTY, name: '화장품·미용', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_SHOPPING, sortOrder: 343 },
  { id: CATEGORY_IDS.EXPENSE_SHOPPING_ELECTRONICS, name: '전자기기', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_SHOPPING, sortOrder: 344 },
  { id: CATEGORY_IDS.EXPENSE_SHOPPING_FURNITURE, name: '가구·인테리어', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_SHOPPING, sortOrder: 345 },
  { id: CATEGORY_IDS.EXPENSE_SHOPPING_OTHER, name: '기타쇼핑', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_SHOPPING, sortOrder: 346 },

  { id: CATEGORY_IDS.EXPENSE_LEISURE_CULTURE, name: '여가·문화', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 350 },
  { id: CATEGORY_IDS.EXPENSE_LEISURE_MOVIE_PERFORMANCE, name: '영화·공연', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LEISURE_CULTURE, sortOrder: 351 },
  { id: CATEGORY_IDS.EXPENSE_LEISURE_GAME, name: '게임', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LEISURE_CULTURE, sortOrder: 352 },
  { id: CATEGORY_IDS.EXPENSE_LEISURE_HOBBY, name: '취미', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LEISURE_CULTURE, sortOrder: 353 },
  { id: CATEGORY_IDS.EXPENSE_LEISURE_TRAVEL, name: '여행', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LEISURE_CULTURE, sortOrder: 354 },
  { id: CATEGORY_IDS.EXPENSE_LEISURE_SPORTS, name: '스포츠', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LEISURE_CULTURE, sortOrder: 355 },
  { id: CATEGORY_IDS.EXPENSE_LEISURE_CONTENT, name: '콘텐츠', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_LEISURE_CULTURE, sortOrder: 356 },

  { id: CATEGORY_IDS.EXPENSE_HEALTH, name: '건강', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 360 },
  { id: CATEGORY_IDS.EXPENSE_HEALTH_HOSPITAL, name: '병원', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_HEALTH, sortOrder: 361 },
  { id: CATEGORY_IDS.EXPENSE_HEALTH_PHARMACY, name: '약국', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_HEALTH, sortOrder: 362 },
  { id: CATEGORY_IDS.EXPENSE_HEALTH_EXERCISE, name: '운동', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_HEALTH, sortOrder: 363 },
  { id: CATEGORY_IDS.EXPENSE_HEALTH_MANAGEMENT, name: '건강관리', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_HEALTH, sortOrder: 364 },

  { id: CATEGORY_IDS.EXPENSE_EDUCATION, name: '교육·자기계발', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 370 },
  { id: CATEGORY_IDS.EXPENSE_EDUCATION_BOOK, name: '도서', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_EDUCATION, sortOrder: 371 },
  { id: CATEGORY_IDS.EXPENSE_EDUCATION_LECTURE, name: '강의', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_EDUCATION, sortOrder: 372 },
  { id: CATEGORY_IDS.EXPENSE_EDUCATION_ACADEMY, name: '학원', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_EDUCATION, sortOrder: 373 },
  { id: CATEGORY_IDS.EXPENSE_EDUCATION_CERTIFICATE, name: '자격증', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_EDUCATION, sortOrder: 374 },
  { id: CATEGORY_IDS.EXPENSE_EDUCATION_TUITION, name: '학비', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_EDUCATION, sortOrder: 375 },

  { id: CATEGORY_IDS.EXPENSE_RELATIONSHIP, name: '모임·관계', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 380 },
  { id: CATEGORY_IDS.EXPENSE_RELATIONSHIP_FRIENDS, name: '친구·모임', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_RELATIONSHIP, sortOrder: 381 },
  { id: CATEGORY_IDS.EXPENSE_RELATIONSHIP_DATE, name: '데이트', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_RELATIONSHIP, sortOrder: 382 },
  { id: CATEGORY_IDS.EXPENSE_RELATIONSHIP_GIFT, name: '선물', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_RELATIONSHIP, sortOrder: 383 },
  { id: CATEGORY_IDS.EXPENSE_RELATIONSHIP_CEREMONY, name: '경조사', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_RELATIONSHIP, sortOrder: 384 },
  { id: CATEGORY_IDS.EXPENSE_RELATIONSHIP_MEMBERSHIP, name: '회비', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_RELATIONSHIP, sortOrder: 385 },

  { id: CATEGORY_IDS.EXPENSE_FINANCE, name: '금융', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 390 },
  { id: CATEGORY_IDS.EXPENSE_FINANCE_FEE, name: '수수료', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FINANCE, sortOrder: 391 },
  { id: CATEGORY_IDS.EXPENSE_FINANCE_INTEREST, name: '이자', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FINANCE, sortOrder: 392 },
  { id: CATEGORY_IDS.EXPENSE_FINANCE_TAX, name: '세금', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FINANCE, sortOrder: 393 },
  { id: CATEGORY_IDS.EXPENSE_INSURANCE_TAX, name: '보험', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FINANCE, sortOrder: 394 },
  { id: CATEGORY_IDS.EXPENSE_DEBT_REPAYMENT, name: '대출상환', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_FINANCE, sortOrder: 395 },

  { id: CATEGORY_IDS.EXPENSE_OTHER, name: '기타', type: 'EXPENSE', purposeType: 'GENERAL', sortOrder: 400 },
  { id: CATEGORY_IDS.EXPENSE_OTHER_EXPENSE, name: '기타지출', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_OTHER, sortOrder: 401 },
  { id: CATEGORY_IDS.EXPENSE_UNCLASSIFIED, name: '미분류', type: 'EXPENSE', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.EXPENSE_OTHER, sortOrder: 402 },

  { id: CATEGORY_IDS.INCOME_SALARY, name: '급여', type: 'INCOME', purposeType: 'GENERAL', parentCategoryId: CATEGORY_IDS.INCOME, sortOrder: 410 },
];
