import type { Request, Response } from 'express';
import { UserFinanceSetting } from '../models';
import { ReportService } from '../services/reportService';
import { nextSalaryDate, dateOnly } from '../utils/dates';
import { AppError } from '../utils/errors';
import { jsonSafe } from '../utils/serialize';

const reports = new ReportService();
export async function home(req: Request, res: Response) { const today = new Date(); const uid = req.authUser!.id; const context = await reports.context(uid, today); const setting = await UserFinanceSetting.findByPk(uid); if (!setting) throw new AppError('FINANCE_SETTING_REQUIRED', 'Finance setting must be created first', 409); const salary = nextSalaryDate(today, Number(setting.salaryDay)); const data = { salaryDay: Number(setting.salaryDay), nextSalaryDate: dateOnly(salary), daysUntilSalary: Math.max(0, Math.ceil((salary.getTime() - today.getTime()) / 86400000)), cycle: { startDate: context.cycle.startDate, projectedEndDate: context.cycle.endDate, status: context.cycle.status }, today: { recommendedAmount: context.result.todayRecommendedAmount, spentAmount: context.result.todayVariableExpenseAmount, remainingToday: context.result.remainingTodayAmount }, budget: { calculationMode: 'CATEGORY_PERCENTAGE_ALLOCATION', salaryAmount: context.result.salaryAmount, savingBudgetAmount: context.result.savingBudgetAmount, investmentBudgetAmount: context.result.investmentBudgetAmount, fixedExpenseBudgetAmount: context.result.fixedExpenseBudgetAmount, usableBudgetAmount: context.result.usableBudgetAmount, variableExpenseAmount: context.result.variableExpenseAmount, fixedExpenseAmount: context.result.fixedExpenseAmount, remainingUsableAmount: context.result.remainingUsableAmount, categories: context.result.categoryProgress }, pace: { status: context.result.paceStatus, difference: context.result.difference }, savingProjection: { potentialExtraSaving: context.result.potentialExtraSaving, confidence: context.result.confidence, sampleDays: context.result.sampleDays } }; res.json({ success: true, data: jsonSafe(data) }); }
