import type { Request, Response } from 'express';
import { UserFinanceSetting } from '../models';
import { ReportService } from '../services/reportService';
import { nextSalaryDate, dateOnly } from '../utils/dates';
import { AppError } from '../utils/errors';
import { jsonSafe } from '../utils/serialize';

const reports = new ReportService();
export async function home(req: Request, res: Response) { const today = new Date(); const uid = req.authUser!.id; const context = await reports.context(uid, today); const setting = await UserFinanceSetting.findByPk(uid); if (!setting) throw new AppError('FINANCE_SETTING_REQUIRED', 'Finance setting must be created first', 409); const salary = nextSalaryDate(today, Number(setting.salaryDay)); const todayKey = dateOnly(today); const spentToday = context.transactions.filter((transaction: any) => transaction.status === 'CONFIRMED' && transaction.type === 'EXPENSE' && dateOnly(new Date(`${transaction.occurredAt}T00:00:00Z`)) === todayKey).reduce((sum: number, transaction: any) => sum + Number(transaction.amount), 0); const data = { salaryDay: Number(setting.salaryDay), nextSalaryDate: dateOnly(salary), daysUntilSalary: Math.max(0, Math.ceil((salary.getTime() - today.getTime()) / 86400000)), cycle: { startDate: context.cycle.startDate, endDate: context.cycle.endDate }, today: { recommendedAmount: context.result.todayRecommendedAmount, spentAmount: spentToday, remainingToday: context.result.todayRecommendedAmount - spentToday }, budget: { remainingFlexibleAmount: context.result.remainingFlexibleAmount, reservedFixedAmount: context.result.reservedScheduledAmount, flexibleBudget: context.result.flexibleBudget, flexibleSpent: context.result.flexibleSpent }, pace: { status: context.result.paceStatus, difference: context.result.difference }, savingProjection: { potentialExtraSaving: context.result.potentialExtraSaving, confidence: context.result.confidence, sampleDays: context.result.sampleDays } }; res.json({ success: true, data: jsonSafe(data) }); }
