import type { Request, Response } from 'express';
import { Op } from 'sequelize';
import { BudgetCycleService } from '../services/budgetCycleService';
import { Category, Transaction } from '../models';
import { parseDateOnly, dateOnly } from '../utils/dates';
import { AppError } from '../utils/errors';
import { jsonSafe } from '../utils/serialize';
import { newId } from '../utils/ids';

const cycleService = new BudgetCycleService(); const uid = (req: Request) => req.authUser!.id;
const ownedCategory = (categoryId: string, userId: string) => Category.findOne({ where: { id: categoryId, isActive: true, [Op.or]: [{ ownerUserId: userId }, { ownerUserId: null }] } });

export async function createTransaction(req: Request, res: Response) { const cycle = await cycleService.findOrCreateForDate(uid(req), parseDateOnly(req.body.occurredAt)); if (!(await ownedCategory(req.body.categoryId, uid(req)))) throw new AppError('INVALID_CATEGORY', 'Category not found', 400); const data = await Transaction.create({ ...req.body, id: newId(), userId: uid(req), budgetCycleId: cycle!.id, amount: String(req.body.amount), occurredAt: req.body.occurredAt, userEdited: true }); res.status(201).json({ success: true, data: jsonSafe(data) }); }
export async function listTransactions(req: Request, res: Response) { const q = req.query as Record<string, string | undefined>; const page = Math.max(1, Number(q.page ?? 1)); const limit = Math.min(100, Math.max(1, Number(q.limit ?? 50))); const where: any = { userId: uid(req), ...(q.categoryId ? { categoryId: q.categoryId } : {}), ...(q.type ? { type: q.type } : {}), ...(q.status ? { status: q.status } : {}) }; if (q.startDate || q.endDate) where.occurredAt = { ...(q.startDate ? { [Op.gte]: q.startDate } : {}), ...(q.endDate ? { [Op.lte]: q.endDate } : {}) }; const [data, total] = await Promise.all([Transaction.findAll({ where, include: [{ model: Category, as: 'category' }], order: [['occurredAt', 'DESC']], offset: (page - 1) * limit, limit }), Transaction.count({ where })]); res.json({ success: true, data: { items: jsonSafe(data), page, limit, total } }); }
export async function getTransaction(req: Request, res: Response) { const data = await Transaction.findOne({ where: { id: String(req.params.id), userId: uid(req) }, include: [{ model: Category, as: 'category' }] }); if (!data) throw new AppError('NOT_FOUND', 'Transaction not found', 404); res.json({ success: true, data: jsonSafe(data) }); }
export async function updateTransaction(req: Request, res: Response) { const item = await Transaction.findOne({ where: { id: String(req.params.id), userId: uid(req) } }); if (!item) throw new AppError('NOT_FOUND', 'Transaction not found', 404); if (req.body.categoryId && !(await ownedCategory(req.body.categoryId, uid(req)))) throw new AppError('INVALID_CATEGORY', 'Category not found', 400); const data = await item.update({ ...req.body, ...(req.body.amount !== undefined ? { amount: String(req.body.amount) } : {}), ...(req.body.occurredAt ? { occurredAt: dateOnly(parseDateOnly(req.body.occurredAt)) } : {}), userEdited: true }); res.json({ success: true, data: jsonSafe(data) }); }
export async function deleteTransaction(req: Request, res: Response) { const result = await Transaction.destroy({ where: { id: String(req.params.id), userId: uid(req) } }); if (!result) throw new AppError('NOT_FOUND', 'Transaction not found', 404); res.json({ success: true, data: { deleted: true } }); }
