import express from 'express';
import cors from 'cors';
import { env } from './config/env';
import { errorHandler, notFoundHandler } from './middleware/errors';
import { financeRoutes } from './routes/financeRoutes';
import { transactionRoutes } from './routes/transactionRoutes';
import { reportRoutes } from './routes/reportRoutes';
import { policyRoutes } from './routes/policyRoutes';
import { fixedExpenseRoutes } from './routes/fixedExpenseRoutes';
import { categoryRoutes } from './routes/categoryRoutes';
import { profileRoutes } from './routes/profileRoutes';
import { authMiddleware } from './middleware/auth';
import { home } from './controllers/dashboardController';
import { notificationRoutes } from './routes/notificationRoutes';

export const app = express();
app.use(cors({ origin: env.CORS_ORIGIN.split(',').map((origin) => origin.trim()) }));
app.use(express.json());
app.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
app.get('/api/home', authMiddleware, home);
app.use('/api/profile', profileRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/finance', financeRoutes);
app.use('/api/transactions', transactionRoutes);
app.use('/api/reports', reportRoutes);
app.use('/api/policies', policyRoutes);
app.use('/api/fixed-expenses', fixedExpenseRoutes);
app.use('/api/categories', categoryRoutes);
app.use(notFoundHandler);
app.use(errorHandler);
